/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInterviewRouteImport } from './routes/ai-interview'
import { Route as CareerMentorRouteImport } from './routes/career-mentor'
import { Route as CoverLetterRouteImport } from './routes/cover-letter'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as JdAnalyzerRouteImport } from './routes/jd-analyzer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResumeAnalyzerRouteImport } from './routes/resume-analyzer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInterviewRoute = AiInterviewRouteImport.update({
  id: '/ai-interview',
  path: '/ai-interview',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerMentorRoute = CareerMentorRouteImport.update({
  id: '/career-mentor',
  path: '/career-mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverLetterRoute = CoverLetterRouteImport.update({
  id: '/cover-letter',
  path: '/cover-letter',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const JdAnalyzerRoute = JdAnalyzerRouteImport.update({
  id: '/jd-analyzer',
  path: '/jd-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeAnalyzerRoute = ResumeAnalyzerRouteImport.update({
  id: '/resume-analyzer',
  path: '/resume-analyzer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-interview': typeof AiInterviewRoute
  '/career-mentor': typeof CareerMentorRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/jd-analyzer': typeof JdAnalyzerRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-interview': typeof AiInterviewRoute
  '/career-mentor': typeof CareerMentorRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/jd-analyzer': typeof JdAnalyzerRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-interview': typeof AiInterviewRoute
  '/career-mentor': typeof CareerMentorRoute
  '/cover-letter': typeof CoverLetterRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRoute
  '/jd-analyzer': typeof JdAnalyzerRoute
  '/login': typeof LoginRoute
  '/resume-analyzer': typeof ResumeAnalyzerRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-interview'
    | '/career-mentor'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/jd-analyzer'
    | '/login'
    | '/resume-analyzer'
    | '/settings'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-interview'
    | '/career-mentor'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/jd-analyzer'
    | '/login'
    | '/resume-analyzer'
    | '/settings'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/ai-interview'
    | '/career-mentor'
    | '/cover-letter'
    | '/dashboard'
    | '/history'
    | '/jd-analyzer'
    | '/login'
    | '/resume-analyzer'
    | '/settings'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInterviewRoute: typeof AiInterviewRoute
  CareerMentorRoute: typeof CareerMentorRoute
  CoverLetterRoute: typeof CoverLetterRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRoute
  JdAnalyzerRoute: typeof JdAnalyzerRoute
  LoginRoute: typeof LoginRoute
  ResumeAnalyzerRoute: typeof ResumeAnalyzerRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-interview': {
      id: '/ai-interview'
      path: '/ai-interview'
      fullPath: '/ai-interview'
      preLoaderRoute: typeof AiInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-mentor': {
      id: '/career-mentor'
      path: '/career-mentor'
      fullPath: '/career-mentor'
      preLoaderRoute: typeof CareerMentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover-letter': {
      id: '/cover-letter'
      path: '/cover-letter'
      fullPath: '/cover-letter'
      preLoaderRoute: typeof CoverLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jd-analyzer': {
      id: '/jd-analyzer'
      path: '/jd-analyzer'
      fullPath: '/jd-analyzer'
      preLoaderRoute: typeof JdAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-analyzer': {
      id: '/resume-analyzer'
      path: '/resume-analyzer'
      fullPath: '/resume-analyzer'
      preLoaderRoute: typeof ResumeAnalyzerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInterviewRoute: AiInterviewRoute,
  CareerMentorRoute: CareerMentorRoute,
  CoverLetterRoute: CoverLetterRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRoute,
  JdAnalyzerRoute: JdAnalyzerRoute,
  LoginRoute: LoginRoute,
  ResumeAnalyzerRoute: ResumeAnalyzerRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
